### ISSUE TITLE
transfer ownership to ensime

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sublime#11]
We had a lot of interest at Scala Days about people wanting to pick up dev on the sublime support for ENSIME. I think it would really help if the top level repo for all the sublime forks were transferred to the ensime organisation, could you pretty please transfer the ownership?

We'll take care of pushing the latest code and so on.

Also asked here but it's not the top level https://github.com/sublimescala/sublime-ensime/issues/99

**Comment by casualjim** [comment]
do I transfer it to your user?

**Comment by casualjim** [comment]
I need admin rights on the ensime org to transfer it. to there.

**Comment by fommil** [comment]
cool! You shouldn't need rights on the other side, just change it to `ensime`. If you can't do that (might be a weird github rule) just change to `fommil` and I can put it to `ensime`.

**Comment by casualjim** [comment]
it really says I need admin rights on the destination.
Now I can let you know when I've done the transfer, and you can kick me out again.

![screenshot from 2015-06-11 10-03-03](https://cloud.githubusercontent.com/assets/456109/8113202/5b0dc49c-1021-11e5-81f6-9b8112e0a5e1.png)

![screenshot from 2015-06-11 10-05-04](https://cloud.githubusercontent.com/assets/456109/8113207/632007b2-1021-11e5-94b4-024e15266a56.png)

**Comment by fommil** [comment]
Heh, I found the docs about that. Pretty would rule.

I'm on a train right now and only have access to the mobile api, which won't give me that kind of access. As a hack you can give it to me and I'll move it onto ensime when I get home. Otherwise, I'll give you admin on ensime when I get home.

**Comment by fommil** [comment]
Rule is only about giving to orgs, BTW, not individuals.

**Comment by casualjim** [comment]
oic, k you have transfer pending

**Comment by fommil** [comment]
Awesome, thanks! I'll transfer to ensime and add you as admin

**Comment by rorygraves** [comment]
Tis done.
