### ISSUE TITLE
Struggles in Mac OS

### ISSUE THREAD

**Issue by pedrofurla** [ensime/ensime-sublime#110]
First problem was making Sublime find SBT:
- Mentioning the `sbt_binary` configuration somewhere would be nice.

Second problem, not sure this one is specific to Mac OS. Staring up Ensime gives back a stacktrace culminating the cryptic error `OSError: [Errno 8] Exec format error`. 
- Not sure why this happens, but the solution was to put the traditional `#!/bin/sh` the beginning of the shell script that executes SBT, the one invoked by sublime-ensime.

**Comment by VC1995** [comment]
Ensime-sublime has been rewritten(#130). It no longer needs path to sbt.
