### ISSUE TITLE
Change style of line errors

### ISSUE THREAD

**Issue by jayd3e** [ensime/ensime-sublime#114]
Is there a way to make line errors more **bold**?  I'm using a dark theme for sublime, and they don't stand out at all.  I've see other plugins put a bright red circle next to the line, which I think works quite well for both light/dark themes.  Thoughts?

**Comment by rorygraves** [comment]
Hi @jayd3e I'm sure there is, the plugin is a bit underloved right now.  - PRs definitely welcome!

**Comment by VC1995** [comment]
In the ensime user settings : "Preferenes" -> "Package Settings" -> "Ensime" -> "Settings-User".
Add the following: 
```
{   ...
    "error_icon": "dot",
    ...
}
```

**Comment by VC1995** [comment]
P.S. The plugin has been rewritten. Check it out :-)
