### ISSUE TITLE
save classpath failed - invalid system property log.noformat - not a valid command: true

### ISSUE THREAD

**Issue by hossameldeen** [ensime/ensime-sublime#117]
## Steps
- Installed sbt 0.13.8
- Installed ensime's v0.11.0 as a plugin to sublime through Package Control. Made sure of the version through `Package Control: List packages`
- Created a simple hello-world project.
- Called `sbt ensimeConfig` inside the directory and .ensime file was created.
- In sublime, ran `Ensime: Startup`. However, it didn't start and got errors in Sublime's terminal, probably the most relevant of which are  

```
... [INFO ] Save classpath task failed with error 1 check
...\Resolution\saveClasspath.log
...
... [INFO ] Failed to start
```
- saveClasspath.log had some logs, probably the most relevant of which are

```
Warning: invalid system property 'sbt.log.noformat'
....
[error] Not a valid command: true
[error] Not a valid project ID: true
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: true (similar: run, runner, target)
[error] true
[error] ^
```
## Why the problem happened
- Ensime calls sbt with the flag `sbt.log.noformat` but sbt doesn't seem to recognize it.
## Solution

Override `sbt_flags` to `[""]` in Ensime-sublime's user settings. More detailed steps (quoting @jrlemieux from gitter's chat)

```
For completeness, I fixed the problem by editing the file "Ensime.sublime-settings" by doing Preferences | Package Settings | Ensime | Settings - User
Adding these lines in the file (I run under Windows 10):
{
"sbt_binary": "C:\Program Files (x86)\sbt\bin\sbt.bat",
"sbt_flags" : [""]
}
```

However, I don't think "sbt_binary" line is needed.
## Notes
- Whether this is a bug or an expected behaviour in sbt, opened an issue there  
  https://github.com/sbt/sbt/issues/2695
- Whether anything more need to be done or no, I don't know.

**Comment by stormcoder** [comment]
I am having the exact same issue.

**Comment by stormcoder** [comment]
This fixed my problem. Thanks.

**Comment by VC1995** [comment]
Ensime-sublime has been rewritten (#130). It no longer runs sbt during startup.
