### ISSUE TITLE
Ensime: Startup - PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by ericchang00** [ensime/ensime-sublime#123]
I'm trying to run `Ensime:Startup` on ST3, Win 8.1 following the standard installation instructions. I get the following error message:

![image](https://cloud.githubusercontent.com/assets/16146623/20470708/9c7490d8-af70-11e6-9df0-549079d1ca03.png)

Running Sublime as administrator doesn't resolve the issue. Any ideas?

**Comment by daron666** [comment]
Got the same on Win7 Pro x64

**Comment by rorygraves** [comment]
This is trying to run ```sbt saveClasspath``` in the .ensimeCache directory - my only suggestion would be to update your config to fully specify the path to sbt - other than that it would need more investigation.

Can you for example cd to the .ensimeCache\resolution directory and run ```sbt saveClasspath``` successfully?

**Comment by daron666** [comment]
@rorygraves Got success with `sbt saveClasspath` but still unable to tun ensime on windows.

**Comment by rorygraves** [comment]
I suspect the path seen by Sublime in process execution is different to you shell. 
Check the docs there is a way of setting the full sbt path which may address the problem.

**Comment by OlafurPa** [comment]
I've got the same problem. sbt saveClasspath succeeds but `Access is denied` in Sublime.

**Comment by VC1995** [comment]
#130

**Comment by VC1995** [comment]
#133
