### ISSUE TITLE
Error when running ensime server from Sublime

### ISSUE THREAD

**Issue by stormcoder** [ensime/ensime-sublime#124]
I am running Sublime on Windows 10 and I am receiving the following error when I run the Ensime Startup command. 
`Warning: invalid system property 'sbt.log.noformat'
[info] Loading global plugins from C:\Users\Owner\.sbt\0.13\plugins
[info] Loading project definition from C:\Users\Owner\Documents\src\POGen\.ensime_cache\Resolution\project
[info] Set current project to resolution (in build file:/C:/Users/Owner/Documents/src/POGen/.ensime_cache/Resolution/)
[error] Not a valid command: true
[error] Not a valid project ID: true
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: true (similar: run, runner, target)
[error] true
[error]     ^
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
`
My plugins.sbt file looks like this
```

resolvers += Resolver.sonatypeRepo("public")

addSbtPlugin("org.ensime" % "sbt-ensime" % "1.12.4")

addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.3")


```
My sublime ensime settings look like this.
`{
	"sbt_binary": "C:\\sbt\\bin\\sbt.bat"
}`

Scala version:
`scalaVersion := "2.11.8"`

Using SBT
`[info] 0.13.13`

My Sublime version
![image](https://cloud.githubusercontent.com/assets/691089/21291983/4f2ce41e-c4b1-11e6-8039-f35d2e378637.png)

**Comment by antoine-sachet** [comment]
Add `"sbt_flags": []` to your settings.

**Comment by VC1995** [comment]
#130
