### ISSUE TITLE
startup issue with scala 2.12 projects

### ISSUE THREAD

**Issue by PSeitz** [ensime/ensime-sublime#125]
When I start the server for scala 2.12 projects I get the following error

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.ensime#ensime_2.12;1.0.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```

When I hardcode the scala version in ensime.py:818 to 2.11.8, everything seems to work.

`write_classpath_sbt_script(build_file, '2.11.8', self.ensime_version, classpath_file)`

I don't understand the implications of the scala version here, would it make sense to hardcode to always use the latest version?

**Comment by rorygraves** [comment]
Ensime sublime needs to be updated to the 2.0 branch which supports 2.12. Right now it only supports Ensime 1.0 version which is 2.10/2.11 only. 

PRs welcome, otherwise it's likely to be blocked until @dickwall gets some free time.
