### ISSUE TITLE
Ensime Port hard coded path

### ISSUE THREAD

**Issue by flurdy** [ensime/ensime-sublime#26]
Does the ensime cache port have to be hard coded to a project? 

"external_server_port_file": "$PROJECT/.ensime_cache/port",

Or be shared across projects?

**Comment by fommil** [comment]
Yup, one server per project by design.

**Comment by fommil** [comment]
Actually the important thing is the cache dir, which doesn't have to be at that location. It can go anywhere.

**Comment by flurdy** [comment]
Problem in Sublime is that is one server for one project for all projects. May just need adding to a different configuration file for sublime

**Comment by flurdy** [comment]
Can the cache be shared? Or perhaps better, the path can be probably extracted from sublime environment variables so that multiple projects with ensime can work.

**Comment by fommil** [comment]
cache can't be shared, it's tied to the JVM/Classpath for each project.

Sounds like there is just a little refactoring within ensime-sublime needed to support multiple projects. Emacs knows which ENSIME server to talk to for each source root and that works well.

**Comment by flurdy** [comment]
Yup, Ill have a dig around to see how to make it project generic.

**Comment by fommil** [comment]
btw, one obvious case of wanting two ENSIME's per project is for the build definitions. Emacs and the server support it but my sbt foo is too weak to work out how to generate the `project/.ensime`.

**Comment by rorygraves** [comment]
@flurdy @fommil  Sorry guys, late to the party.  
As per the temporary documentation, this s a hack.  What should happen is the Sublime plugin should run the equivalent of the serverStart.sh and use the constructed part to connect.

The hack means that we can get this going without having to fix the whole initialisation process - and either I or someone will hopefully fix it soon (currently working on fixing the completion and UTF-8 issues.
