### ISSUE TITLE
Hello, Ensime Sublime can't find the external Server Port file since it will not be created

### ISSUE THREAD

**Issue by schmitch** [ensime/ensime-sublime#28]
Here is my error message: 
```
"connect_to_external_server" in your Ensime.sublime-settings is set to true, however "external_server_port_file" is set to a non-existent file "/Users/schmitch/projects/envisia/envisia-erp-loki/.ensime_cache/port" . Check the configuration and restart Ensime.```

Also what i found out is that people need to install coreutils on mac via brew install coreutils

**Comment by wulftone** [comment]
did you find a solution for this?  I'm having the same issue.

**Comment by rorygraves** [comment]
@wulftone Did you manually start the server as per the instructions?
See the readme: https://github.com/ensime/ensime-sublime

Ensime-Sublime is still a bit rough round the edges.
If you did start the server by using the runServer.sh script, is it still running, if not, what does the log say (it will have terminated for a reason).

thanks

**Comment by schmitch** [comment]
@rorygraves @wulftone This is not a bug, you just need to start the server and wait, after a while the started server will print out some additional staff, after that you could run Ensime Startup inside Sublime Text, btw. after a month things get better and better.

**Comment by rorygraves** [comment]
Thanks @schmitch yep. Definitely getting better. I have just finished the server changes so that Sublime can launch the server automatically. Probably get it in this weekend ;).
