### ISSUE TITLE
Ensime server doesn't handle non-ascii charsets

### ISSUE THREAD

**Issue by dcsobral** [ensime/ensime-sublime#3]
If the error messages produced by the operating system as non-ASCII, one might get an error like this:

    Starting Ensime Server at Ensime\server

    Traceback (most recent call last):
      File ".\sublime_plugin.py", line 325, in run_
      File ".\ensime_server.py", line 188, in run
      File ".\ensime_server.py", line 212, in append_data
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 21: ordinal not in range(128)

Something like this does get rid of the problem, but mangles the error messages:

    self.output_view.insert(edit, self.output_view.size(), ''.join([c for c in str if 32 <= ord(c) < 128]))

That's the line 212 mentioned in the traceback.

**Comment by rorygraves** [comment]
Probably still a bug - but closing for now.
