### ISSUE TITLE
Jump to not working

### ISSUE THREAD

**Issue by mbk** [ensime/ensime-sublime#31]
At least for me, in either single or multi-build projects.

Server log:

```
22:00:23.620 [default-akka.actor.default-dispatcher-3] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:ok (:name "com.work.miffy.consumer.QueueConsumer" :local-name "QueueConsumer" :type (:name "QueueConsumer" :type-id 1 :full-name "com.work.miffy.consumer.QueueConsumer" :decl-as class :pos t) :decl-pos (:file "/Volumes/Work/miffy/src/main/scala/com/work/miffy/consumer/QueueConsumer.scala" :offset 1835) :owner-type-id 2)) 3)
```

Then the client gets:

```
[2015-06-26 00:03:43.725496]: XXX Got msg_id 1  payload [:ok, [:name, u'com.work.miffy.consumer.QueueConsumer', :local-name, u'QueueConsumer', :type, [:name, u'QueueConsumer', :type-id, 1, :full-name, u'com.work.miffy.consumer.QueueConsumer', :decl-as, class, :pos, True], :decl-pos, [:file, u'/Volumes/Work/miffy/src/main/scala/com/work/miffy/consumer/QueueConsumer.scala', :offset, 1835], :owner-type-id, 2]]
```

And the sublime console says:

```
Traceback (most recent call last):
  File "./rpc.py", line 331, in callback
  File "./rpc.py", line 25, in parse
  File "./rpc.py", line 67, in populate
  File "./rpc.py", line 25, in parse
  File "./rpc.py", line 85, in populate
  File "./rpc.py", line 22, in parse
  File "./sexp.py", line 29, in sexp_to_key_map
Exception: not a sexp: True
```

**Comment by rorygraves** [comment]
Ah there is a protocol error on the client side. There have been a number of breaks that I've been fixing as I go. I don't have any tests (yet), this should be an easy fix.

**Comment by mbk** [comment]
Awesome.

Op vrijdag 26 juni 2015 heeft Rory Graves (@a_dev_musing) <
notifications@github.com> het volgende geschreven:

**Comment by rorygraves** [comment]
I hate to say 'can you try switching it off and on again, but thats the summary of the below ;)

Something funky is going on here - ```:pos t``` is not valid - it should be either ```:pos nil``` (no position) or ```:pos (...)```( Some(pos)).  I added some checks on the server side (locally so far) to test all 4 responses and they all look good.

Can you clean ensime out of your .ivy cache and try and rerun.  If it reoccurs after a fresh download can you also give the request message here in case there is something more funky here.

**Comment by mbk** [comment]
I am running ensime out of a seprate directory per in instructions. What patch of the cache do you want me to clean?

Also, I noted on OSX that I had the `greadline` in the startServer.sh to jus $1 to get things working.

**Comment by rorygraves** [comment]
The script uses sbt to download ensime - I was suggesting you clear  ~/.ivy2/cache/org.ensime and  ~/.ivy2/local/org.ensime (if you have one) to force it to redownload the ensime jars. 
This makes sure you are bang upto date with the ensime version - hopefully this issue will then magically resolve.

**Comment by mbk** [comment]
Ok, I'll try over the weekend and report back

**Comment by mbk** [comment]
Nope - didn't work :(
