### ISSUE TITLE
Error decoding ensime's reply

### ISSUE THREAD

**Issue by dcsobral** [ensime/ensime-sublime#7]
I'm getting this error when trying to check the type of something:

    SEND: (:swank-rpc (swank:type-at-point "C:\\Users\\Daniel\\Desktop\\github\\Dojo\\scala\\segundo\\src\\test\\scala\\CalcTest.scala" 804) 4)
    RECV: 0002bb(:return (:ok (:name "(result: org.specs2.matcher.ExpectedParsedResult[Int])org.specs2.matcher.Matcher[CalcTest.this.parsers.Parser[Int]]" :type-id 3 :arrow-type t :result-type (:name "Matcher" :type-id 6 :full-name "org.specs2.matcher.Matcher" :decl-as trait :type-args ((:name "Parser" :type-id 5 :full-name "scala.util.parsing.combinator.Parsers$Parser" :decl-as class :type-args ((:name "Int" :type-id 1 :full-name "scala.Int" :decl-as class)) :outer-type-id 4))) :param-sections ((:params (("result" (:name "ExpectedParsedResult" :type-id 2 :full-name "org.specs2.matcher.ExpectedParsedResult" :decl-as class :type-args ((:name "Int" :type-id 1 :full-name "scala.Int" :decl-as class))))))))) 4)
    on_data: [:return, [:ok, [:name, '(result: org.specs2.matcher.ExpectedParsedResult[Int])org.specs2.matcher.Matcher[CalcTest.this.parsers.Parser[Int]]', :type-id, 3, :arrow-type, True, :result-type, [:name, 'Matcher', :type-id, 6, :full-name, 'org.specs2.matcher.Matcher', :decl-as, trait, :type-args, [[:name, 'Parser', :type-id, 5, :full-name, 'scala.util.parsing.combinator.Parsers$Parser', :decl-as, class, :type-args, [[:name, 'Int', :type-id, 1, :full-name, 'scala.Int', :decl-as, class]], :outer-type-id, 4]]], :param-sections, [[:params, [['result', [:name, 'ExpectedParsedResult', :type-id, 2, :full-name, 'org.specs2.matcher.ExpectedParsedResult', :decl-as, class, :type-args, [[:name, 'Int', :type-id, 1, :full-name, 'scala.Int', :decl-as, class]]]]]]]]], 4]
    Traceback (most recent call last):
      File ".\ensime_client.py", line 250, in on_data
      File ".\ensime_client.py", line 197, in <lambda>
      File ".\ensime_notes.py", line 115, in handle_reply
    TypeError: cannot concatenate 'str' and 'bool' objects

**Comment by rorygraves** [comment]
Closing for now - needs retesting on updated project.
