### ISSUE TITLE
How to manage the multiple projects?

### ISSUE THREAD

**Issue by tagia0212** [ensime/ensime-sublime#71]
Hi, thank you for this great ST plugin.

I read readme and can use this plugin.
btw, how to manage the multiple projects?

Environment `PROJECT` can be set for only a project...

**Comment by dickwall** [comment]
Right now, if you start ensime using sublime (use sbt gen-ensime to create the project first, then open the folder in a new sublime text window and start ensime there), you should be able to run separate ensime projects for separate window/folder combinations, however there is no project shutdown at the moment so after you open a few of them, it's a good idea to quit sublime every so often and just re-open the ones you want.
