### ISSUE TITLE
Issue starting ensime server

### ISSUE THREAD

**Issue by bikerdan** [ensime/ensime-sublime#75]
When trying to start ensime server I'm getting:
"Error: Could not find or load main class org.ensime.server.Server"

I've deleted the .ensime and .ensime_cache resources.  I've deleted my ivy cache.

Not sure what's going on...  Any ideas?

**Comment by rorygraves** [comment]
Assuming you are starting from within Sublime via PackageControl, can you make sure you have the latest version from Package Control (0.4) and paste in your console log (View -> Show Console) of the Ensime:Startup, that should give us some clues as to what is failing?

Thanks

Rory

**Comment by bikerdan** [comment]
Actually, I was trying to start the ensime server as described in the README of this project, on the commandline.  

If I try to start it through sublime without the server running I get:
"[Ensime] 2015-11-03 15:41:15,010 [ERROR]  "connect_to_external_server" in your Ensime.sublime-settings is set to true, however "external_server_port_file" is set to a non-existent file "/Users/asdf/Projects/neuralmodelapi/.ensime_cache/port" . Check the configuration and restart Ensime.
ERROR:ensime:"connect_to_external_server" in your Ensime.sublime-settings is set to true, however "external_server_port_file" is set to a non-existent file "/Users/asdf/Projects/neuralmodelapi/.ensime_cache/port" . Check the configuration and restart Ensime.
error: "connect_to_external_server" in your Ensime.sublime-settings is set to true, however "external_server_port_file" is set to a non-existent file "/Users/asdf/Projects/neuralmodelapi/.ensime_cache/port" . Check the configuration and restart Ensime.
Unable to open /Users/asdf/Library/Application Support/Sublime Text 3/Packages/Ensime/Ensime.sublime-settings"

**Comment by rorygraves** [comment]
Sorry, readme is out of date, will fix tomorrow.  I failed to update the serverStart.sh to match a change in the server dependencies.

**Comment by bikerdan** [comment]
No problem.  So all i should need to do is run Ensime: Starup on the popup menu of sublime?

**Comment by rorygraves** [comment]
It should be - certainly worked for me ;)

**Comment by bikerdan** [comment]
Yeah.  So when I try it, I'm getting the error above about the port.  The same error I used to get when I'd try to run ensime in sublime without starting the server.

**Comment by bikerdan** [comment]
Found the issue!  

I have used this plugin for a while now.  Before the server was built in to the plugin, you would have to set the "connect_to_external_server" setting to true.  Setting this back to the default of false solved my issue.

Hope this helps anyone else having this problem!
