### ISSUE TITLE
Fail to start Ensime Server

### ISSUE THREAD

**Issue by ssanj** [ensime/ensime-sublime#76]
I've installed Ensime through the package manager. I'm trying to start the server through the command palette command "Ensime: Startup". I get the following errors:

```
No ensime environment for  7
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 439, in is_enabled_
    ret = self.is_enabled()
  File "ensime in /Users/sanjivsahayam/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 1870, in is_enabled
  File "ensime in /Users/sanjivsahayam/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 2066, in can_show
AttributeError: 'NoneType' object has no attribute '_output'
```

I've created a sublime project and generated a .ensime file as well.

Any ideas?

**Comment by rorygraves** [comment]
So you added your source root to the window (Project -> Add Folder to project), and then tried Ensime: Startup?  The error message is bad, but the implication is that it has failed to find the .ensime file.
Can you try opening one of the scala files from within the project and trying again?

Thanks

Rory

**Comment by ssanj** [comment]
Hey Rory,

I hadn't done that because I created a .sublime-project with:

```
{
	"folders":
	[
		{
			"path": "."
		}
	]
}
```
So I manually added the project folder to the project as you recommended. That got me passed the error. 

Now I get a different error when trying to start the server:

```
[Ensime] 2015-11-05 09:16:50,790 [ERROR]  "connect_to_external_server" in your Ensime.sublime-settings is set to true, however "external_server_port_file" is set to a non-existent file "/Users/sanjivsahayam/projects/OtherLevels/tools/ans-query/.ensime_cache/port" . Check the configuration and restart Ensime.
error: "connect_to_external_server" in your Ensime.sublime-settings is set to true, however "external_server_port_file" is set to a non-existent file "/Users/sanjivsahayam/projects/OtherLevels/tools/ans-query/.ensime_cache/port" . Check the configuration and restart Ensime.
```

**Comment by ssanj** [comment]
Got it working by following @bikerdan's advice on issue #75 . :)

**Comment by bikerdan** [comment]
Awesome!  Glad it's already helped someone. :)
