### ISSUE TITLE
Project specific settings

### ISSUE THREAD

**Issue by danapsimer** [ensime/ensime-sublime#80]
Currently there is no way to override ensime settings per project.  For instance, it would be nice to be able to specify the SBT binary for different projects.  Also, I have one very large project that needs bigger memory settings for the sbt build to work, but I'd rather not give the build more memory for my other, smaller projects.

**Comment by VC1995** [comment]
This doesn't seem as an ensime-sublime issue and should have gone to [ensime-server](https://github.com/ensime/ensime-server/issues).
Also I think it's now possible :), do checkout latest developments on ensime-server
