### ISSUE TITLE
The ST3 plugin for Ensime creates invalid SBT build file (build.sbt) on Windows

### ISSUE THREAD

**Issue by mskcode** [ensime/ensime-sublime#81]
# Issue abstract
Trying to use Ensime-plugin for Sublime Text 3 on Windows does not work; the ensime process will not run because of an error in the SBT build file: ./.ensime_cache/Resolution/build.sbt.

# How to reproduce
1. Install Ensime-plugin for Sublime Text 3 as instructed on Windows platform
2. Start the Ensime-engine from ST3 as instructed using "Ensime: Startup" command
3. Check the produced log file saveClasspath.log for following error: [error] [REDACTED\\.ensime_cache\Resolution\build.sbt]:34: invalid escape character

Issue can also be reproduced after the first initial failure from the command line by executing commands:

    > cd [path to .ensime_cache/Resolution directory]
    > sbt saveClasspath

# Cause of the issue
The issue is caused by the generated build.sbt file where the line

    val out = file("D:\REDACTED\HelloScala\.ensime_cache\Resolution\classpath")

contains invalid string escape sequences because of the Windows path separator. The correct form should be:

    val out = file("D:\\REDACTED\\HelloScala\\.ensime_cache\\Resolution\\classpath")

An even simpler way to fix the issue (assuming that the file paths do not require escape sequences) would be to use Scala raw string:

    val out = file(raw"D:\REDACTED\HelloScala\.ensime_cache\Resolution\classpath")

The Python code that generates the aforementioned line is found from

    file: server.py, line: 55

and assuming that the simple fix is used, the line should read

    |   val out = file(""" + 'raw"' + classpath_file + '"' + """)

**Comment by rorygraves** [comment]
Thanks for the awesome bug report - fixed in v0.6.0 and deployed to PC
